# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

# np.zeros()會產生全部都是0的陣列
# np.empty()則是產生極小且接近0的陣列
# np.empty()用於建立一個初始array，但不在意裡面的數值，可以用速度比較快的empty

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
# 記得先 Import 正確的套件

import numpy as np

In [37]:
# 參考解答

a = np.random.rand(2, 3)
print(a)
a = np.array(a,dtype=int)
print(a)

print("\n------------\n")
a = np.random.rand(2,3)
a = a*100
print(a.round())
print(np.around(a))

[[0.91331414 0.74707711 0.20423549]
 [0.71796789 0.81117984 0.95202957]]
[[0 0 0]
 [0 0 0]]

------------

[[50. 17. 27.]
 [56. 15. 73.]]
[[50. 17. 27.]
 [56. 15. 73.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [47]:
m = 20
n = 40

# 利用平移的概念

a = np.random.rand(2,3) * (n-m)
print(a)

# b%1 等於 b除以1的餘數，所以就會得到小數點後所有數字，相減後就會變成整數

b = a 
print((a - b%1)+m)

[[12.24868179 12.47289093 16.67955697]
 [ 8.66546789 12.75529235  3.78971795]]
[[32. 32. 36.]
 [28. 32. 23.]]
