# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [8]:
import numpy as np
a = np.random.random((5, 5))
print("a :",a ,"\n\n----------------------------------\n")
print(a.sum()) 
print(np.sum(a))
print(sum(a))

# a.sum() 和 np.sum()都是屬於numpy專屬的，結果相同。
# sum(a)則是array和list都能使用，但他是將array根據axis=0(欄)來做加總。

a : [[0.54693485 0.00184311 0.42702208 0.61492626 0.50847453]
 [0.38603094 0.22479658 0.68845665 0.69755133 0.88801291]
 [0.18594277 0.66222685 0.32526537 0.23682516 0.35082811]
 [0.05012482 0.9429105  0.58057449 0.95850514 0.06551316]
 [0.0573382  0.14892302 0.23463726 0.96453709 0.99724415]] 

----------------------------------

11.745445313905902
11.745445313905902
[1.22637159 1.98070006 2.25595584 3.47234498 2.81007286]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [30]:
A = np.random.random((5, 5))

A = (A-A.min()) / (A.max() - A.min())
print(A)

[[0.42380385 0.83222755 0.6489271  0.02311573 0.59816567]
 [0.98431595 0.78793251 0.50587777 0.1387302  0.        ]
 [0.90038838 0.84300141 0.19535298 0.38869299 0.94362951]
 [0.24280096 0.84505978 0.92139804 0.40998763 1.        ]
 [0.52670076 0.31795534 0.7275752  0.78963372 0.4873556 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [29]:
a = np.arange(1,11,1)
a[a==a.max()] = -1
print(a)

print("\n---------------------\n")

a = np.arange(1,11,1)
a[a.argmax()] = -1
print(a)

[ 1  2  3  4  5  6  7  8  9 -1]

---------------------

[ 1  2  3  4  5  6  7  8  9 -1]
